# theme = "kanagawa_t"
theme = "rose_pinet"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
bufferline = "multiple"
soft-wrap = { enable = true }
idle-timeout = 0
# whitespace.render = {newline="all"}


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-signature-help-docs = true
display-inlay-hints = true
# inline-diagnostics = { max-warp = 1 }

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

[keys.normal]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
